version: '2'
services:
  myappdb:
    build: mysql
    volumes:
      - myappdb:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
  
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - myappdb
volumes:
  myappdb:
